name: tatame-monorepo

services:
  postgres:
    image: postgres
    container_name: tatame-monorepo-postgres
    environment:
      POSTGRES_DB: tatame-monorepo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - tatame-monorepo_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  tatame-monorepo_postgres_data:
